services:
  - type: web
    name: spx-academy-api
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app

  - type: static_site
    name: spxacademy
    rootDir: frontend
    buildCommand: corepack enable && corepack prepare pnpm@9.12.3 --activate && pnpm install --no-frozen-lockfile && pnpm run build
    staticPublishPath: dist
    envVars:
      - key: NODE_VERSION
        value: 20.19.5
